In [ ]:
import sys

print(sys.byteorder)
print(sys.getsizeof(1))
print(sys.platform)
print(sys.version_info.major)
print(sys.version_info.minor)


little
28
win32
3
10


In [ ]:
import os

print(os.getcwd())
os.environ['LOGLEVEL'] = 'DEBUG'
print(os.environ.get('LOGLEVEL'))
print(os.getlogin())

c:\Users\s0983\Documents\github\python-DevOps-practice
DEBUG
s0983


In [26]:
import subprocess

cp = subprocess.run(
    ['powershell', 'ls'],
    capture_output=True,
    universal_newlines=True
)

print("輸出：")
print(cp.stdout)
print("回傳碼：", cp.returncode)

Exception in thread Thread-64 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\s0983\miniconda3\envs\python-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "c:\Users\s0983\miniconda3\envs\python-env\lib\site-packages\ipykernel\ipkernel.py", line 772, in run_closure
    _threading_Thread_run(self)
  File "c:\Users\s0983\miniconda3\envs\python-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\s0983\miniconda3\envs\python-env\lib\subprocess.py", line 1515, in _readerthread
    buffer.append(fh.read())
  File "c:\Users\s0983\miniconda3\envs\python-env\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 8: invalid start byte


輸出：
None
回傳碼： 0


In [6]:
from numba import jit
import numpy as np

# 第一次呼叫 sum2d 時做 JIT 編譯，之後呼叫就直接用編譯後的機器碼執行，速度會快很多
@jit
def sum2d(arr):
    M, N = arr.shape
    result = 0.0
    for i in range(M):
        for j in range(N):
            result += arr[i, j]
    return result

a = np.arange(9).reshape(3, 3)
print(a)
print(sum2d(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36.0


In [7]:
from numba import jit, njit
import numpy as np

# 在 nopython=True 模式下，若 Numba 不能完全編譯成機器碼，會直接報錯，能幫你確認是否真的在跑 JIT。  
@njit  # 或 @jit(nopython=True)
def sum_matrix_njit(M):
    N1, N2 = M.shape
    result = 0
    for i in range(N1):
        for j in range(N2):
            result += M[i, j]
    return result

x = np.arange(100).reshape(10, 10)
print(sum_matrix_njit(x))

4950
